version: 0.2

env:
  secrets-manager:
    SLACK_BOT_TOKEN: okzSlackBotToken
    SLACK_CHANNEL: okzSlackChannel

phases:
  install:
    commands:
      - echo Entered the install phase...
      - node -v
      - - npm install
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Lets do CDK Deploy...
      - cdk deploy -c stage=dev --require-approval never
  post_build:
    commands:
      - python3 afterDeploy.py
